version: '3'

services:
  backend:
    container_name: employees_api
    image: node:14-alpine
    ports:
      - 3000:3000
    working_dir: /backend
    volumes:
      - ./:/backend
    env_file:
      - .env
    command: tail -f /dev/null
  db:
    container_name: db_container
    image: mysql:8.0.31
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
